feat(docs) : How contrib
ElectronicCats/CatSniffer pull request #70
Opened 2024-03-27 15:27 UTC by JahazielLem

- Show how PyCatSniffer works and how contribute

2024-03-27 16:28 UTC, sabas1080 approved these changes

2024-04-09 19:37 UTC, sabas1080 commented
Actualizar con respecto al nuevo CLA https://github.com/ElectronicCats/electroniccats-cla por favor

2024-04-09 19:38 UTC, sabas1080 requested changes
Actualizar con respecto al nuevo CLA https://github.com/ElectronicCats/electroniccats-cla por favor

2024-04-09 21:29 UTC, REGIOIGER approved these changes

2024-04-22 17:49 UTC, sabas1080 commented
@JahazielLem any update??

2024-04-29 17:17 UTC, sabas1080 approved these changes

2024-04-29 17:17 UTC, merged